# Generated by Django 5.1.6 on 2025-03-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
