# Generated by Django 5.1.6 on 2025-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('profesor', 'Profesor'), ('estudiante', 'Estudiante'), ('administrador', 'Administrador')], default='estudiante', max_length=13),
        ),
    ]
